// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, name, description, date, location, price, start_time, status
FROM events
ORDER BY date ASC
`

type GetAllEventsRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Date        time.Time      `json:"date"`
	Location    string         `json:"location"`
	Price       string         `json:"price"`
	StartTime   time.Time      `json:"start_time"`
	Status      EventStatus    `json:"status"`
}

// Retrieves a list of all events in the catalog.
func (q *Queries) GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEventsRow
	for rows.Next() {
		var i GetAllEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Date,
			&i.Location,
			&i.Price,
			&i.StartTime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, name, description, date, location, price, start_time, status
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Date        time.Time      `json:"date"`
	Location    string         `json:"location"`
	Price       string         `json:"price"`
	StartTime   time.Time      `json:"start_time"`
	Status      EventStatus    `json:"status"`
}

// Retrieves a single event by its ID.
func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Date,
		&i.Location,
		&i.Price,
		&i.StartTime,
		&i.Status,
	)
	return i, err
}
