// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const resetInventory = `-- name: ResetInventory :exec
UPDATE inventory
SET available_tickets = $2,
    version = 1
WHERE event_id = $1
`

type ResetInventoryParams struct {
	EventID          uuid.NullUUID `json:"event_id"`
	AvailableTickets int32         `json:"available_tickets"`
}

func (q *Queries) ResetInventory(ctx context.Context, arg ResetInventoryParams) error {
	_, err := q.db.ExecContext(ctx, resetInventory, arg.EventID, arg.AvailableTickets)
	return err
}
