// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: engine.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (user_id, event_id, status, expires_at)
VALUES ($1, $2, 'pending', NOW() + INTERVAL '10 minutes')
returning id, user_id, event_id, status, expires_at, created_at, updated_at
`

type CreateReservationParams struct {
	UserID  uuid.NullUUID `json:"user_id"`
	EventID uuid.NullUUID `json:"event_id"`
}

// Creates a new reservation for a user and event.
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, createReservation, arg.UserID, arg.EventID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT id, event_id, version,  available_tickets
FROM inventory
WHERE event_id = $1
`

// Retrieves the current inventory for a given event.
func (q *Queries) GetInventory(ctx context.Context, eventID uuid.NullUUID) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, eventID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Version,
		&i.AvailableTickets,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
RETURNING id
`

type InsertIdempotencyKeyParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Key    string        `json:"key"`
}

// Inserts a new idempotency key for a user.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertIdempotencyKey, arg.UserID, arg.Key)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateInventoryAtomic = `-- name: UpdateInventoryAtomic :execrows
UPDATE inventory
SET version = version + 1,
    available_tickets = available_tickets - $2
WHERE event_id = $1 
AND version = $3
AND available_tickets >= $2
`

type UpdateInventoryAtomicParams struct {
	EventID          uuid.NullUUID `json:"event_id"`
	AvailableTickets int32         `json:"available_tickets"`
	Version          int32         `json:"version"`
}

// Updates the inventory for a given event atomically.
func (q *Queries) UpdateInventoryAtomic(ctx context.Context, arg UpdateInventoryAtomicParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInventoryAtomic, arg.EventID, arg.AvailableTickets, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
