// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Creates a new reservation for a user and event.
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	// Creates a new user with the given email and password hash.
	CreateUser(ctx context.Context, arg CreateUserParams) error
	// Retrieves a list of all events in the catalog.
	GetAllEvents(ctx context.Context) ([]GetAllEventsRow, error)
	// Retrieves a single event by its ID.
	GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error)
	// Retrieves the current inventory for a given event.
	GetInventory(ctx context.Context, eventID uuid.NullUUID) (Inventory, error)
	// Retrieves a reservation by its ID, including event details.
	GetReservation(ctx context.Context, id uuid.UUID) (GetReservationRow, error)
	GetReservationStatus(ctx context.Context, id uuid.UUID) (ReservationStatus, error)
	// Retrieves a user by their email address.
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// Inserts a new idempotency key for a user.
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (uuid.UUID, error)
	MarkReservationExpired(ctx context.Context, id uuid.UUID) (int64, error)
	RefundPostgresInventory(ctx context.Context, eventID uuid.NullUUID) error
	// Updates the inventory for a given event atomically.
	UpdateInventoryAtomic(ctx context.Context, arg UpdateInventoryAtomicParams) (int64, error)
	// Updates the status of a reservation.
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error
}

var _ Querier = (*Queries)(nil)
