// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Creates a new reservation for a user and event.
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	// Retrieves the current inventory for a given event.
	GetInventory(ctx context.Context, eventID uuid.NullUUID) (Inventory, error)
	// Inserts a new idempotency key for a user.
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (uuid.UUID, error)
	// Updates the inventory for a given event atomically.
	UpdateInventoryAtomic(ctx context.Context, arg UpdateInventoryAtomicParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
