// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getReservationStatus = `-- name: GetReservationStatus :one
SELECT status FROM reservations WHERE id = $1
`

func (q *Queries) GetReservationStatus(ctx context.Context, id uuid.UUID) (ReservationStatus, error) {
	row := q.db.QueryRowContext(ctx, getReservationStatus, id)
	var status ReservationStatus
	err := row.Scan(&status)
	return status, err
}

const markReservationExpired = `-- name: MarkReservationExpired :execrows
UPDATE reservations 
SET status = 'expired', updated_at = NOW() 
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkReservationExpired(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReservationExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refundPostgresInventory = `-- name: RefundPostgresInventory :exec
UPDATE inventory 
SET available_tickets = available_tickets + 1 
WHERE event_id = $1
`

func (q *Queries) RefundPostgresInventory(ctx context.Context, eventID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, refundPostgresInventory, eventID)
	return err
}
